sudo: required
language: java

jdk:
  - oraclejdk8

env:
  - TERM=dumb

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y wine
  
before_script: 
  - cd de.peeeq.wurstscript
  - chmod +x gradlew

script:
  - ./gradlew assemble test --info
  
after_success:
  - ./gradlew jacocoTestReport coveralls
